class SizeUtils {
  SizeUtils._();

  //base container padding and margin
  static const double basePadding = 10;
  static const double basePaddingMargin2 = 2;
  static const double basePaddingMargin3 = 3;
  static const double basePaddingMargin4 = 4;
  static const double basePaddingMargin5 = 5;
  static const double basePaddingMargin6 = 6;
  static const double basePaddingMargin8 = 8;
  static const double basePaddingMargin9 = 9;
  static const double basePaddingMargin10 = 10;
  static const double basePaddingMargin12 = 12;
  static const double basePaddingMargin13 = 13;
  static const double basePaddingMargin14 = 14;
  static const double basePaddingMargin16 = 16;
  static const double basePaddingMargin18 = 18;
  static const double basePaddingMargin20 = 20;
  static const double basePaddingMargin22 = 22;
  static const double basePaddingMargin24 = 24;
  static const double basePaddingMargin26 = 26;
  static const double basePaddingMargin28 = 28;
  static const double basePaddingMargin30 = 30;
  static const double basePaddingMargin32 = 32;
  static const double basePaddingMargin34 = 34;
  static const double basePaddingMargin36 = 36;
  static const double basePaddingMargin45 = 45;
  static const double basePaddingMargin53 = 53;
  static const double basePaddingMargin62 = 62;
  static const double basePaddingMargin64 = 64;
  static const double basePaddingMargin68 = 68;
  static const double basePaddingMargin72 = 72;
  static const double basePaddingMargin80 = 80;
  static const double basePaddingMargin100 = 100;
  static const double basePaddingMargin128 = 128;
  static const double basePaddingMargin11 = 11;
  static const double basePaddingMargin56 = 56;

  //etc
  static const double baseRoundedCorner = 8;
  static const double baseRoundedCorner4 = 4;
  static const double baseRoundedCorner10 = 10;
  static const double baseRoundedCorner12 = 12;
  static const double baseRoundedCorner15 = 15;
  static const double baseRoundedCorner20 = 20;
  static const double baseRoundedCorner24 = 24;
  static const double baseRoundedCorner30 = 30;
  static const double baseRoundedCorner50 = 50;
  static const double baseRoundedCorner100 = 100;
  static const double baseRoundedCorner200 = 200;
  static const double baseBlurRadius = 4;
  static const double baseSpreadRadius = 2;
  static const double baseOffsetX = 0;
  static const double baseOffsetY = 3;
  static const double baseViewportFraction88 = 0.88;
  static const double baseViewportFraction85 = 0.85;

  //base container width and height
  static const double baseWidthHeight1 = 1;
  static const double baseWidthHeight2 = 2;
  static const double baseWidthHeight4 = 4;
  static const double baseWidthHeight6 = 6;
  static const double baseWidthHeight8 = 8;
  static const double baseWidthHeight10 = 10;
  static const double baseWidthHeight12 = 12;
  static const double baseWidthHeight13 = 13;
  static const double baseWidthHeight14 = 14;
  static const double baseWidthHeight16 = 16;
  static const double baseWidthHeight17 = 17;
  static const double baseWidthHeight18 = 18;
  static const double baseWidthHeight20 = 20;
  static const double baseWidthHeight22 = 22;
  static const double baseWidthHeight24 = 24;
  static const double baseWidthHeight26 = 26;
  static const double baseWidthHeight28 = 28;
  static const double baseWidthHeight30 = 30;
  static const double baseWidthHeight32 = 32;
  static const double baseWidthHeight33 = 33;
  static const double baseWidthHeight38 = 38;
  static const double baseWidthHeight40 = 40;
  static const double baseWidthHeight72 = 72;
  static const double baseWidthHeight48 = 48;
  static const double baseWidthHeight52 = 52;
  static const double baseWidthHeight54 = 54;
  static const double baseWidthHeight56 = 56;
  static const double baseWidthHeight50 = 50;
  static const double baseWidthHeight60 = 60;
  static const double baseWidthHeight65 = 65;
  static const double baseWidthHeight66 = 66;
  static const double baseWidthHeight70 = 70;
  static const double baseWidthHeight75 = 75;
  static const double baseWidthHeight80 = 80;
  static const double baseWidthHeight90 = 90;
  static const double baseWidthHeight96 = 96;
  static const double baseWidthHeight100 = 100;
  static const double baseWidthHeight105 = 105;
  static const double baseWidthHeight110 = 110;
  static const double baseWidthHeight120 = 120;
  static const double baseWidthHeight123 = 123;
  static const double baseWidthHeight150 = 150;
  static const double baseWidthHeight155 = 155;
  static const double baseWidthHeight160 = 160;
  static const double baseWidthHeight165 = 165;
  static const double baseWidthHeight170 = 170;
  static const double baseWidthHeight185 = 185;
  static const double baseWidthHeight200 = 200;
  static const double baseWidthHeight210 = 210;
  static const double baseWidthHeight214 = 214;
  static const double baseWidthHeight140 = 140;
  static const double baseWidthHeight142 = 142;
  static const double baseWidthHeight190 = 190;
  static const double baseWidthHeight240 = 240;
  static const double baseWidthHeight250 = 250;
  static const double baseWidthHeight265 = 265;
  static const double baseWidthHeight280 = 280;
  static const double baseWidthHeight290 = 290;
  static const double baseWidthHeight300 = 300;
  static const double baseWidthHeight310 = 310;
  static const double baseWidthHeight248 = 248;
  static const double baseWidthHeight296 = 296;
  static const double baseWidthHeight295 = 295;
  static const double baseWidthHeight588 = 588;
  static const double baseWidthHeight64 = 64;
  static const double baseWidthHeight42 = 42;
  static const double baseWidthHeight44 = 44;
  static const double baseWidthHeight25 = 25;
  static const double baseWidthHeight135 = 135;
  static const double baseWidthHeight156 = 156;
  static const double baseWidthHeight464 = 464;
  static const double baseWidthHeight350 = 350;
  static const double baseWidthHeight410 = 410;
  static const double baseWidthHeight445 = 445;
  static const double baseWidthHeight485 = 485;

  // base text size
  static const double baseTitleSize = 16;
  static const double baseTextSize4 = 4;
  static const double baseTextSize8 = 8;
  static const double baseTextSize10 = 10;
  static const double baseTextSize12 = 12;
  static const double baseTextSize13 = 13;
  static const double baseTextSize14 = 14;
  static const double baseTextSize16 = 16;
  static const double baseTextSize18 = 18;
  static const double baseTextSize20 = 20;
  static const double baseTextSize24 = 24;
  static const double baseTextSize26 = 26;
  static const double baseTextSize28 = 28;
  static const double baseTextSize30 = 30;
  static const double baseTextSize32 = 32;
  static const double baseTextSize52 = 52;

  // base positioned
  static const double basePositioned16 = 16;
  static const double basePositioned150 = 150;
  static const double basePositioned175 = 175;
  static const double basePositioned190 = 190;

  static const double baseLineText = 1.5;
  static const double baseLineText1 = 1;
  static const double baseWidthDivider = 0.5;
  static const double baseToolbarHeight64 = 64;

  //icon size
  static const double baseIconMenuSize = 59;
}
